"""
Configuration - Complete parameters for production
"""

# Binance API
BINANCE_BASE_URL = "https://api.binance.com"
SYMBOL_FILTER_SUFFIX = "USDT"

# Timeframes
TIMEFRAMES = ["15m", "1h", "4h"]
MAIN_TIMEFRAME = "15m"

# === PREFILTERS ===
MIN_24H_QUOTE_VOLUME = 5_000_000  # $5M minimum volume
MIN_PRICE_USDT = 0.02  # Filter penny stocks
MIN_24H_CHANGE = -15.0  # Max 15% drop
MAX_24H_CHANGE = 20.0  # Max 20% pump

# Signal Settings
COOLDOWN_MINUTES = 60
MAX_SYMBOLS_PER_SCAN = 50  # Limit to top 50 by volume

# Telegram
ENABLE_TELEGRAM = True  # Set True and add credentials
TELEGRAM_BOT_TOKEN = "8501728555:AAH0_P304u36Z8PLTLQIb_07Pf9U3jwkj1U"
TELEGRAM_CHAT_ID = "-1003424647080"

# API Settings
REQUEST_TIMEOUT = 10
MAX_RETRIES = 3
RETRY_BACKOFF = 2

# Logging
LOG_CSV_PATH = "signals_log.csv"
LOG_LEVEL = "INFO"

# === SIGNAL THRESHOLDS ===
ULTRA_BUY_SCORE = 12
STRONG_BUY_SCORE = 8

# ULTRA_BUY Requirements
ULTRA_BUY_MIN_TREND = 3
ULTRA_BUY_MIN_OSC = 2
ULTRA_BUY_MIN_VOL_PA = 3
ULTRA_BUY_MAX_RSI = 65

# STRONG_BUY Requirements
STRONG_BUY_MIN_TREND = 2
STRONG_BUY_MIN_OSC = 1
STRONG_BUY_MIN_VOL_PA = 2

# === INDICATOR PARAMETERS ===
# Moving Averages
EMA_FAST = 20
EMA_SLOW = 50

# Trend
ADX_PERIOD = 14
ADX_STRONG_TREND = 20.0
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MACD_HIST_RISING_BARS = 3
MOMENTUM_PERIOD = 10

# Oscillators
RSI_PERIOD = 14
RSI_HEALTHY_MIN = 45
RSI_HEALTHY_MAX = 65
STOCH_K_PERIOD = 14
STOCH_D_PERIOD = 3
STOCH_OVERSOLD = 20
STOCH_OVERBOUGHT = 80
CCI_PERIOD = 20
WILLIAMS_PERIOD = 14
WILLIAMS_BULLISH = -60
UO_PERIODS = (7, 14, 28)
UO_BULLISH = 50

# Volume
OBV_TREND_LOOKBACK = 10
VOLUME_SPIKE_MULTIPLIER = 1.5
VOLUME_LOOKBACK = 20

# Price Action
MIN_BODY_PCT = 1.0  # 1% minimum candle body
COLLAPSE_MAX_DROP_PCT = 12.0
COLLAPSE_LOOKBACK_BARS = 96
MIN_BAR_VOLUME_USDT = 10000

# Backtest
BACKTEST_TP_PERCENTS = [2.0, 3.0, 5.0, 10.0]
BACKTEST_SL_PERCENTS = [1.0, 2.0, 3.0]
BACKTEST_LOOKAHEAD_BARS = 96