"""
Configuration - Complete parameters for production
"""

# Binance API
BINANCE_BASE_URL = "https://api.binance.com"
SYMBOL_FILTER_SUFFIX = "USDT"

# Timeframes
TIMEFRAMES = ["15m", "1h", "4h"]
MAIN_TIMEFRAME = "15m"

# === PREFILTERS ===
MIN_24H_QUOTE_VOLUME = 10_000_000  # $10M minimum volume per revised spec
MIN_PRICE_USDT = 0.04  # Filter illiquid penny assets
MIN_24H_CHANGE = -10.0  # Reject symbols dumping more than 10%
MAX_24H_CHANGE = 20.0  # Reject symbols pumping beyond 20%

# Signal Settings
COOLDOWN_MINUTES = 60
MAX_SYMBOLS_PER_SCAN = 50  # Limit to top 50 by volume

# Telegram
ENABLE_TELEGRAM = True  # Set True and add credentials
TELEGRAM_BOT_TOKEN = "8501728555:AAH0_P304u36Z8PLTLQIb_07Pf9U3jwkj1U"
TELEGRAM_CHAT_ID = "-1003424647080"

# API Settings
REQUEST_TIMEOUT = 10
MAX_RETRIES = 3
RETRY_BACKOFF = 2

# Logging
LOG_CSV_PATH = "signals_log.csv"
LOG_LEVEL = "INFO"

# === SIGNAL THRESHOLDS (legacy, retained for telemetry) ===
ULTRA_BUY_SCORE = 12
STRONG_BUY_SCORE = 8
ULTRA_BUY_MIN_TREND = 3
ULTRA_BUY_MIN_OSC = 2
ULTRA_BUY_MIN_VOL_PA = 3
ULTRA_BUY_MAX_RSI = 65
STRONG_BUY_MIN_TREND = 2
STRONG_BUY_MIN_OSC = 1
STRONG_BUY_MIN_VOL_PA = 2

# Block toggles (Phase 3 future-ready hooks)
ENABLE_TREND_BLOCK = True
ENABLE_OSC_BLOCK = True
ENABLE_VOLUME_BLOCK = True
ENABLE_PRICE_ACTION_BLOCK = True

# === INDICATOR PARAMETERS ===
# Moving Averages
EMA_FAST = 20
EMA_SLOW = 50

# Trend
ADX_PERIOD = 14
ADX_STRONG_TREND = 20.0
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MACD_HIST_RISING_BARS = 3
MOMENTUM_PERIOD = 10

# Oscillators
RSI_PERIOD = 14
RSI_HEALTHY_MIN = 45
RSI_HEALTHY_MAX = 65
STOCH_K_PERIOD = 14
STOCH_D_PERIOD = 3
STOCH_OVERSOLD = 20
STOCH_OVERBOUGHT = 80
CCI_PERIOD = 20
WILLIAMS_PERIOD = 14
WILLIAMS_BULLISH = -60
UO_PERIODS = (7, 14, 28)
UO_BULLISH = 50

# Volume
OBV_TREND_LOOKBACK = 10
VOLUME_SPIKE_MULTIPLIER = 1.5
VOLUME_LOOKBACK = 20

# Price Action
MIN_BODY_PCT = 1.0  # 1% minimum candle body
COLLAPSE_MAX_DROP_PCT = 20.0
COLLAPSE_LOOKBACK_BARS = 96
MIN_BAR_VOLUME_USDT = 10000
EMA_BREAK_LOOKBACK = 10
EMA_RETEST_LOOKBACK = 10
EMA_NEAR_TOLERANCE = 0.01  # 1% proximity check for EMA20 retest detection
EMA_SIMILARITY_TOLERANCE = 0.01  # EMA20 considered ~ EMA50 when within 1%
STRONG_GREEN_BODY_MULTIPLIER = 1.5  # strong vs average body size
STRONG_GREEN_LOOKBACK = 20
LONG_WICK_MIN_RATIO = 0.40

# Volume scoring helpers
VOLUME_SPIKE_STRONG = 1.5
VOLUME_SPIKE_MEDIUM = 1.2
OBV_UPTREND_MIN_PCT = 2.0
OBV_SIDEWAYS_MIN_PCT = 0.5
BULL_POWER_DOMINANCE = 0.0  # Bull power must be > 0 and bear < 0 for bonus

# Higher timeframe confirmation
HTF_EMA_SLOPE_LOOKBACK = 5
HTF_SLOPE_MIN_PCT = 0.0  # Slope must be non-negative for bonus

# Risk tagging thresholds
RISK_LATE_PUMP_CHANGE = 15.0
RISK_VOL_STRONG = 3
RISK_TREND_WEAK = 2

# Core score thresholds (Phase 3 revised spec)
CORE_SCORE_WATCH_MIN = 8
CORE_SCORE_STRONG_MIN = 11
CORE_SCORE_ULTRA_MIN = 14
TREND_MIN_FOR_STRONG = 3
VOL_MIN_FOR_STRONG = 2
TREND_MIN_FOR_ULTRA = 4
OSC_MIN_FOR_ULTRA = 3
VOL_MIN_FOR_ULTRA = 3
HTF_MIN_FOR_ULTRA = 2

# Oscillator / momentum guardrails
RSI_STRONG_MIN = 50
RSI_STRONG_MAX = 65
RSI_BUFFER_MIN = 45
RSI_BUFFER_MAX = 70
STOCH_K_MIDLINE = 50
CCI_STRONG_THRESHOLD = 100
STOCH_RSI_BULL_LEVEL = 50
UO_RISING_MIN_DELTA = 0.5

# Backtest
BACKTEST_TP_PERCENTS = [2.0, 3.0, 5.0, 10.0]
BACKTEST_SL_PERCENTS = [1.0, 2.0, 3.0]
BACKTEST_LOOKAHEAD_BARS = 96